### ISSUE TITLE
DistributionNotFound Error

### ISSUE THREAD

**Issue by tomsambala** [CZ-NIC/fred-client#1]
Hi, 

I'm trying to install FRED client on Ubuntu 18.04 as instructed on installation section [here](https://github.com/CZ-NIC/fred-client/#installation) but whenever I run ./fred-client I encounter the error below:

_pkg_resources.DistributionNotFound: The 'fred-client==2.14.1' distribution was not found and is required by the application_

Thanks in advance.

**Comment by trapaholics** [comment]
Found what I was doing wrong. After running _pip install --upgrade /path-to-packages/_ , the command works now.

Thanks
